### ISSUE TITLE
Hybrid Index

### ISSUE THREAD

**Issue by glaudelrio** [btmartin721/ClineHelpR#18]
Hi! I would like to know whether there is a way to provide the hybrid index (admixture coefficient), calculated in previous analysis, in ClineHelpR like in HIEST: https://cran.r-project.org/web/packages/HIest/HIest.pdf

The idea is to avoid classifying individuals in discrete  populations, but rather use a continuous measure of admixture coefficient.

Thank you so much!

**Comment by btmartin721** [comment]
Hello. BGC estimates the hybrid index, but currently there is not a way to provide it as input into the analysis. Were you wanting to provide it as input to the Phi plots? If so, those use the estimated hybrid index to plot the genomic clines on the X-axis.
