### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by glaudelrio** [btmartin721/ClineHelpR#20]
I got it running with genind2bcg, but once I try to run:

bcg.genes I got an error although I have the files in the indicated directory.

![Screen Shot 2022-05-02 at 3 48 33 PM](https://user-images.githubusercontent.com/10550113/166325371-693c6cef-0274-4429-a177-a30a92855366.png)

Any ideas on what is wrong? 
Thank you very much!

**Comment by btmartin721** [comment]
Hi. it's hard to tell here, but for some reason it isn't finding the input files. Are you sure that you provided the correct path to the input directory?

Are you using Windows? If so, you might need the drive name, such as "C:", placed before "/Users". But it depends on your operating system and computer setup.

Could you try running this R command?

```getwd()```

just before ```combine_bgc_output()``` and show me what it prints out? And also could you try running:

```dir()```

in R and show me what it prints out? That will show the directories that are present in your current working directory.

**Comment by glaudelrio** [comment]
Hi! Thank you so much! I am working in the results directory just in case.
![Screen Shot 2022-05-02 at 5 07 05 PM](https://user-images.githubusercontent.com/10550113/166335226-88e8548f-8259-4edc-a943-05aeee6cfb51.png)
as you can see in the image, my files are in the results directory. 
Thank you!

**Comment by btmartin721** [comment]
I fixed the file naming issue in the run_bgc.sh script. Now it correctly names the lnl file as lnl instead of ln1 when running estpost. But in your case you can just rename the lnl file instead of rerunning the whole script.

**Comment by glaudelrio** [comment]
Sounds good! Does it mean that I need to start a new container for the new function to run?
Thank you!

**Comment by glaudelrio** [comment]
Changing the ln1 to lnl alone did not fix the problem. Thank you so much for the help and sorry for the inconvenience.

**Comment by btmartin721** [comment]
Regarding the container, I will have to rebuild it in order to get run_bgc.sh to run, but I didn't change any of the R files so you shouldn't need a new container to get it to run. 

Regarding the LnL file, I just realized that I made it to where it has to be capital L's like this:

```prefix_LnL_[replicateNumber]```

Could you try changing the L's to capital and let me know if it works?

Sorry for the confusion. I will change it to where it is not case sensitive anymore when I get home tonight.

-Bradley

**Comment by glaudelrio** [comment]
Hi Bradley, thank you so much! Changing it to capital letters solved the issue! Now the issue is in the run per se... my plot traces look like this:

![image](https://user-images.githubusercontent.com/10550113/166613837-a908d23b-edfc-436d-9f21-12c992542c38.png)

any idea on what could be causing this?
Thank you so much!

**Comment by btmartin721** [comment]
Hi. I apologize for my delayed reply. Glad you were able to get it to load. 

I am not 100% sure why the likelihoods are all 0. Do they appear to be equal to or close to 0 in the LnL file generated by BGC? Just trying to determine if this is a BGC or ClineHelpR issue.

Thanks,

-Bradley
